### ISSUE TITLE
More analytics on the data

### ISSUE THREAD

**Issue by rahulrajpl** [imdevskp/covid-19-india-data#1]
Hi Devakumar,

I have done some analytics on your data. Check out: http://randomwalk.in/covid-19-india-data/line/ . Would you be interested in adding this to your repo? If yes, I can submit a PR and further we can work together to create something really good for public use. 

Let me know,

Cheers, Rahul

**Comment by imdevskp** [comment]
There are different people using this data. We can work on it, but I can't make any change to the data file.

**Comment by rahulrajpl** [comment]
I am running this. Take a look and comment on how to make it more useful. 
http://randomwalk.in/covid19India/

**Comment by imdevskp** [comment]
Good job @rahulrajpl
