### ISSUE TITLE
Incorrect figures

### ISSUE THREAD

**Issue by chitransh89** [imdevskp/covid-19-india-data#2]
Delta change in data wasn't captured instead everyday data is taken. Hence there is a mismatch from the original numbers. Total IN-Nat cases in Kerala for instance is 25 in mohfw but the complete data csv says 87.

**Comment by imdevskp** [comment]
The data shows the cumulative count of numbers every day for each state. I don't see Kerala says 87 anywhere in the dataset. Can you please clarify?

**Comment by chitransh89** [comment]
Oh! Absence of a readme file blurred the clarity. Your csv had a count against each day, I thought that's the number of new cases that day. When I cross checked with mohfw website, I got it. It could have been helpful had you put some metadata in readme file for anybody directly looking at your csv.
Nevertheless closing the issue. Thanks.
