### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hritikkounsal** [imdevskp/covid-19-india-data#3]
Due to change in website front end the web scrapping code isn't working properly.

**Comment by Hritikkounsal** [comment]
please resolve it asap

**Comment by imdevskp** [comment]
I had fixed the code this morning and pushed the update. Please run the code again and let me know.

**Comment by Hritikkounsal** [comment]
No, it's not working.
Have a look 
https://www.mohfw.gov.in/

**Comment by Hritikkounsal** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-5-af0947c59284> in <module>
      7 thead = soup.find_all('thead')
      8 print(thead)
----> 9 head = thead.find_all('tr')
     10 
     11 tbody = soup.find_all('tbody')[2]

~\Anaconda3\lib\site-packages\bs4\element.py in __getattr__(self, key)
   2079         """Raise a helpful exception to explain a common code fix."""
   2080         raise AttributeError(
-> 2081             "ResultSet object has no attribute '%s'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?" % key
   2082         )

AttributeError: ResultSet object has no attribute 'find_all'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

**Comment by mohithxoxo** [comment]
thead = soup.find_all('thead')
**head = thead.find_all('tr')**    --<    ERROR at this point

ResultSet object has no attribute 'find_all'. You're probably treating a list of items like a single item. Did you call find_all() when you meant to call find()?


PLEASE find solve it.

**Comment by imdevskp** [comment]
Earlier the patch did not fix the issue. Please see the notebook now.
