### ISSUE TITLE
There is some issue with latest data.

### ISSUE THREAD

**Issue by rahulrajpl** [imdevskp/covid-19-india-data#5]
![image](https://user-images.githubusercontent.com/279503/78099901-f35cf900-7400-11ea-92a7-24bd29cd6a44.png)

**Comment by rahulrajpl** [comment]
Could you please comment on these zero values? Or can we assume data is no longer reliable from your repo?

**Comment by imdevskp** [comment]
MoFHW doesn't update total confirmed cases as Indian and foreigner separately. They changed the format of the table. You can see this here https://www.mohfw.gov.in/. They might change the data format again. For now this how the data is available.
